-- Physique critiques generated by Claude (copy-prompt → CC → POST-back), anchored
-- to the gated measurement state so they don't drift with daily lighting.
-- shape_change_md is authoritative (silhouette + numbers); visible_detail_md is
-- advisory and lighting-dependent. See shc/vision/METHODOLOGY.md.

CREATE TABLE IF NOT EXISTS physique_critiques (
    id                VARCHAR PRIMARY KEY,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    model             VARCHAR NOT NULL DEFAULT 'claude',
    -- gated state this critique is anchored to (staleness basis)
    basis_w2s         DOUBLE,
    basis_w2h         DOUBLE,
    verdict           VARCHAR,          -- leaner | stable | softer | baseline
    shape_change_md   TEXT NOT NULL,    -- authoritative: silhouette + numbers
    visible_detail_md TEXT              -- advisory: from photo, lighting-dependent
);

INSERT INTO schema_version (version) VALUES (30) ON CONFLICT DO NOTHING;
