-- Migration 0059: exercise-science evidence layer — remaining 13 muscles (pass 3).
--
-- Completes the curated+cited rollout: chest, triceps, front_delts, lats,
-- mid_back, rear_delts, side_delts, traps, forearms, quads, hamstrings, calves,
-- abs, adductors, lower_back. Same standard as 0057/0058 — every row carries a
-- real citation (Consensus literature). Catalog gaps flagged in the briefs:
-- forearms (no wrist flexion/extension movements) and adductors (no isolation)
-- are trained only via cross-mapped compounds until movements are added.

-- The same movement develops several muscles (a squat builds quads, glutes, and
-- adductors), so exercise_science is keyed by (exercise_name, muscle), not
-- exercise_name alone. Recreate with the composite key, preserving 0057/0058.
CREATE TABLE exercise_science_v2 (
    exercise_name TEXT NOT NULL,
    muscle        TEXT NOT NULL,
    region        TEXT,
    length_bias   TEXT NOT NULL,
    rep_low       INTEGER NOT NULL,
    rep_high      INTEGER NOT NULL,
    sfr_tier      TEXT NOT NULL DEFAULT 'moderate',
    rationale     TEXT NOT NULL,
    citation      TEXT NOT NULL,
    citation_url  TEXT,
    PRIMARY KEY (exercise_name, muscle)
);
INSERT INTO exercise_science_v2 SELECT exercise_name, muscle, region, length_bias,
    rep_low, rep_high, sfr_tier, rationale, citation, citation_url FROM exercise_science;
DROP TABLE exercise_science;
ALTER TABLE exercise_science_v2 RENAME TO exercise_science;

-- chest
INSERT INTO muscle_development VALUES ('chest', '["upper_chest","mid_chest","lower_chest"]', 'lengthened', 12, 20, 2, '6-12 reps on presses, 10-20 on flyes; lead with a deep-stretch fly or stretched-bottom press', 'Cover all three pec regions across the week by varying bench inclination: 30 degrees biases the upper pec, flat (0 degrees) maximizes mid and lower portions, and decline or dips hit the lower fibers; flyes loaded in the stretched position add a lengthened stimulus. Two sessions per week and roughly 12-20 direct sets sit on the upward part of the dose-response curve before returns diminish.', 'Rodriguez-Ridao 2020', 'https://consensus.app/papers/details/1f48810dc708534c86d0eaf4ba2b79d0/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Incline Chest Fly (Dumbbell)', 'chest', 'upper_chest', 'lengthened', 10, 20, 'moderate', 'Loads the pec in a deep stretched position with the shoulder flexed, biasing the upper fibers; lengthened-position training tends to produce equal or greater hypertrophy than short-length work.', 'Wolf 2025', 'https://consensus.app/papers/details/323adf57b77b557186682fbdd052508c/'),
  ('Chest Fly (Dumbbell)', 'chest', 'mid_chest', 'lengthened', 10, 20, 'moderate', 'Flat dumbbell fly stretches the mid pec under load at the bottom; exercise selection drives where hypertrophy occurs, so a stretch-loaded isolation complements the presses.', 'Zabaleta-Korta 2021', 'https://consensus.app/papers/details/015e6eebfb79567c904dfcf253bb5b1c/'),
  ('Incline Bench Press (Barbell)', 'chest', 'upper_chest', 'mid', 6, 10, 'high', 'A 30 degree incline produces the highest EMG activation of the upper pectoralis major; heavy-loadable compound for upper-chest mass.', 'Rodriguez-Ridao 2020', 'https://consensus.app/papers/details/1f48810dc708534c86d0eaf4ba2b79d0/'),
  ('Bench Press (Barbell)', 'chest', 'mid_chest', 'mid', 6, 10, 'high', 'Flat (0 degree) bench press maximizes EMG activity of the mid and lower pectoralis portions; primary heavy press for overall chest.', 'Rodriguez-Ridao 2020', 'https://consensus.app/papers/details/1f48810dc708534c86d0eaf4ba2b79d0/'),
  ('Bench Press (Dumbbell)', 'chest', 'mid_chest', 'lengthened', 8, 12, 'high', 'Dumbbells allow a deeper bottom position than a barbell, increasing the stretch on the mid pec while remaining a loadable press.', 'Christian 2022', 'https://consensus.app/papers/details/0ab37d1b88d05daf8a34c2dbac8f7c0f/'),
  ('Decline Bench Press (Barbell)', 'chest', 'lower_chest', 'mid', 6, 12, 'moderate', 'Decline pressing emphasizes the lower pectoralis fibers and elicits lower anterior-deltoid involvement than incline, keeping stimulus on the pec.', 'Christian 2022', 'https://consensus.app/papers/details/0ab37d1b88d05daf8a34c2dbac8f7c0f/'),
  ('Dip (Chest)', 'chest', 'lower_chest', 'lengthened', 8, 15, 'moderate', 'Forward-leaning dips load the lower pec in a deep stretched bottom position, adding a lengthened lower-chest stimulus.', 'Wolf 2025', 'https://consensus.app/papers/details/323adf57b77b557186682fbdd052508c/')
ON CONFLICT DO NOTHING;
-- triceps
INSERT INTO muscle_development VALUES ('triceps', '["long_head","lateral_head","medial_head"]', 'lengthened', 10, 18, 2, '6-12 reps on close-grip presses and dips, 10-20 on extensions; lead with an overhead (lengthened) extension for the long head', 'The long head is biarticular and only fully stretched with the shoulder flexed, so an overhead extension is required to bias it; the lateral and medial heads are driven by pushdowns and close-grip pressing. Training the long head overhead produced substantially greater hypertrophy than a neutral arm position even at lower loads. Roughly 10-18 direct sets across two sessions covers all three heads on the productive part of the dose-response curve.', 'Maeo 2022', 'https://consensus.app/papers/details/60c0db596c4858c9af327b98318c102c/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Overhead Tricep Extension (Cable)', 'triceps', 'long_head', 'lengthened', 10, 20, 'high', 'Overhead arm position lengthens the biarticular long head; cable overhead extension produced 1.4-1.5 fold greater triceps hypertrophy than a neutral position even with lighter loads.', 'Maeo 2022', 'https://consensus.app/papers/details/60c0db596c4858c9af327b98318c102c/'),
  ('Overhead Tricep Extension (Dumbbell)', 'triceps', 'long_head', 'lengthened', 10, 20, 'moderate', 'Same overhead-stretch principle as the cable version; shoulder flexion places the long head at long muscle length, which favors hypertrophy.', 'Maeo 2022', 'https://consensus.app/papers/details/60c0db596c4858c9af327b98318c102c/'),
  ('Skull Crusher (Barbell)', 'triceps', 'long_head', 'lengthened', 8, 15, 'moderate', 'With the arms angled back the long head is partially lengthened; the long head generates the most force at low shoulder elevation, making this a useful loadable long-head movement.', 'Kholinne 2018', 'https://consensus.app/papers/details/be5962a3a481555d8e146f9d66e93bd0/'),
  ('Close Grip Bench Press (Barbell)', 'triceps', 'medial_head', 'mid', 6, 10, 'high', 'Heavy elbow-extension compound; at and above 90 degrees of shoulder elevation the medial head carries the highest force, and close-grip pressing keeps the shoulder neutral while loading the triceps heavily.', 'Kholinne 2018', 'https://consensus.app/papers/details/be5962a3a481555d8e146f9d66e93bd0/'),
  ('Dip (Tricep)', 'triceps', 'lateral_head', 'mid', 8, 12, 'moderate', 'Upright dips with the shoulder neutral emphasize the lateral and medial heads through elbow extension; complements the overhead long-head work.', 'Alves 2018', 'https://consensus.app/papers/details/09a2723ba3125c08aca5307c9e3e4f07/'),
  ('Tricep Pushdown (Cable)', 'triceps', 'lateral_head', 'shortened', 10, 20, 'high', 'Neutral shoulder position with the long head shortened shifts emphasis to the lateral and medial heads; high stimulus-to-fatigue isolation for the short-length end of the range.', 'Alves 2018', 'https://consensus.app/papers/details/09a2723ba3125c08aca5307c9e3e4f07/')
ON CONFLICT DO NOTHING;
-- front_delts
INSERT INTO muscle_development VALUES ('front_delts', '["anterior_deltoid"]', 'lengthened', 6, 12, 2, '6-12 reps on presses, 10-20 on raises; 1-2 direct movements since pressing already loads the front delt heavily', 'The anterior deltoid receives heavy indirect work from all horizontal and vertical pressing, so it usually needs only one to two direct movements per week. Overhead/shoulder pressing drives the highest anterior-deltoid activation, and bench inclinations above 45 degrees sharply increase front-delt involvement. Keep direct volume modest (about 6-12 sets) to avoid overlap with chest pressing while still sitting on the productive dose-response range.', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Overhead Press (Barbell)', 'front_delts', 'anterior_deltoid', 'mid', 6, 10, 'high', 'Shoulder press elicits the highest anterior-deltoid activation of the common shoulder exercises; primary heavy-loadable front-delt builder.', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/'),
  ('Overhead Press (Dumbbell)', 'front_delts', 'anterior_deltoid', 'lengthened', 8, 12, 'high', 'Dumbbells allow a deeper bottom position lengthening the front delt; barbell and machine pressing both strongly excite the anterior deltoid during the press.', 'Coratella 2022', 'https://consensus.app/papers/details/933c50f25e9452d3bdff10c6a3f24418/'),
  ('Incline Bench Press (Barbell)', 'front_delts', 'anterior_deltoid', 'mid', 6, 10, 'moderate', 'Bench inclinations above 45 degrees produce significantly higher anterior-deltoid EMG, so a high-incline press doubles as front-delt work.', 'Rodriguez-Ridao 2020', 'https://consensus.app/papers/details/1f48810dc708534c86d0eaf4ba2b79d0/'),
  ('Arnold Press (Dumbbell)', 'front_delts', 'anterior_deltoid', 'lengthened', 8, 12, 'moderate', 'The rotating dumbbell press starts from a flexed, lengthened front-delt position; pressing is the top driver of anterior-deltoid activation.', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/'),
  ('Front Raise (Dumbbell)', 'front_delts', 'anterior_deltoid', 'mid', 10, 20, 'moderate', 'Isolation that targets the anterior deltoid directly through shoulder flexion; useful higher-rep accessory once pressing volume is accounted for.', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/')
ON CONFLICT DO NOTHING;
-- lats
INSERT INTO muscle_development VALUES ('lats', '["lats"]', 'lengthened', 10, 18, 2, '6-12 compound, 10-15 isolation', 'Lat width responds to weekly set volume in a dose-response manner with diminishing returns past moderate volumes; the lats are maximally stretched overhead, and loaded lengthened positions drive hypertrophy, so lead with vertical pulls where the arms reach overhead. Two sessions per week distributes volume without a clear frequency penalty for hypertrophy.', 'Pelland 2025', 'https://consensus.app/papers/details/28976bf04deb591980a56525e2ba77d1/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Pull-Up', 'lats', 'lats', 'lengthened', 6, 10, 'high', 'At the dead-hang top the lats are fully elongated overhead, placing the muscle under load in a deep stretch; pull-ups produce among the highest lat recruitment of vertical pulls.', 'Asayama 2021', 'https://consensus.app/papers/details/e6e148b81373525abf9305379f074096/'),
  ('Chin-Up', 'lats', 'lats', 'lengthened', 6, 10, 'high', 'Supinated grip keeps the lats loaded through a full overhead-to-contracted range; the elongated start position is where loaded stretch most strongly drives growth.', 'Sola 1973', 'https://consensus.app/papers/details/a90fa35549085a268c09b81f2116c3c5/'),
  ('Lat Pulldown (Cable)', 'lats', 'lats', 'lengthened', 8, 12, 'high', 'Cable pulldown reproduces the overhead lengthened lat position with adjustable load, letting trained lifters accumulate stretch-biased volume; loaded stretch is a primary hypertrophy stimulus.', 'Warneke 2023', 'https://consensus.app/papers/details/2dc1bd15d17d56b199c0aa8b897417cf/'),
  ('Lat Pulldown - Close Grip (Cable)', 'lats', 'lats', 'lengthened', 8, 12, 'high', 'Close neutral grip extends the range the lats travel through into adduction while preserving the overhead stretched start; effective for stretch-mediated lat development.', 'Asayama 2021', 'https://consensus.app/papers/details/e6e148b81373525abf9305379f074096/'),
  ('Bent Over Row (Barbell)', 'lats', 'lats', 'mid', 6, 10, 'moderate', 'Horizontal rows load the lats through a more mid-range arc rather than the overhead stretch, complementing vertical pulls; heavy multiset rowing adds total weekly lat volume.', 'Currier 2023', 'https://consensus.app/papers/details/d7159f4e02555ec4bfbe3a35124223f4/'),
  ('Single Arm Row (Dumbbell)', 'lats', 'lats', 'mid', 8, 12, 'moderate', 'Unilateral row allows a long mid-range pull with a supported trunk; useful for adding fractional lat volume which scales hypertrophy with diminishing returns.', 'Heaselgrave 2019', 'https://consensus.app/papers/details/a0d0502d1f1853dd813eb99046dfd8df/')
ON CONFLICT DO NOTHING;
-- mid_back
INSERT INTO muscle_development VALUES ('mid_back', '["rhomboids","mid_traps"]', 'lengthened', 8, 14, 2, '8-12 compound, 12-15 isolation', 'The scapular retractors (rhomboids and middle trapezius) are trained by horizontal pulls; the protracted start of a row places them at length before retraction. Grip and shoulder position shift the trapezius-to-rhomboid ratio, so vary row angles. Volume scales hypertrophy with diminishing returns, and twice-weekly frequency is sufficient.', 'Fennell 2016', 'https://consensus.app/papers/details/2b0920ea7963522d81c58cffa8ee9f48/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Cable Row', 'mid_back', 'rhomboids', 'lengthened', 8, 12, 'high', 'The protracted reach at the start of a seated cable row lengthens the rhomboids and middle traps before retraction loads them; constant cable tension keeps the retractors engaged through range.', 'Fennell 2016', 'https://consensus.app/papers/details/2b0920ea7963522d81c58cffa8ee9f48/'),
  ('Seated Cable Row', 'mid_back', 'mid_traps', 'lengthened', 8, 12, 'high', 'Seated row strongly recruits the scapular retractors, exceeding lat pulldown for these muscles; the long protracted-to-retracted path biases the mid-back.', 'Franke 2015', 'https://consensus.app/papers/details/ab93e0552cc854ff9b69ae274a7f4e67/'),
  ('Seated Cable Row - V Grip (Cable)', 'mid_back', 'rhomboids', 'mid', 10, 14, 'high', 'Neutral V-grip lets the elbows drive back into deep retraction, emphasising the rhomboids; row position raises rhomboid involvement relative to externally rotated arm positions.', 'Fennell 2016', 'https://consensus.app/papers/details/2b0920ea7963522d81c58cffa8ee9f48/'),
  ('Bent Over Row (Barbell)', 'mid_back', 'mid_traps', 'mid', 6, 10, 'moderate', 'Heavy bent-over rowing loads the scapular retractors with high tension; higher-load multiset rowing ranks among the most effective prescriptions for back hypertrophy.', 'Currier 2023', 'https://consensus.app/papers/details/d7159f4e02555ec4bfbe3a35124223f4/'),
  ('T-Bar Row', 'mid_back', 'rhomboids', 'mid', 8, 12, 'moderate', 'Supported chest angle allows heavy retraction-biased loading of the rhomboids and mid traps; adding row volume scales mid-back hypertrophy with diminishing returns.', 'Heaselgrave 2019', 'https://consensus.app/papers/details/a0d0502d1f1853dd813eb99046dfd8df/'),
  ('Face Pull', 'mid_back', 'mid_traps', 'shortened', 12, 20, 'high', 'High-rep face pulls bias the middle trapezius and external rotators in a retracted, shortened position; complements heavier rows for balanced scapular retractor development.', 'Fennell 2016', 'https://consensus.app/papers/details/2b0920ea7963522d81c58cffa8ee9f48/')
ON CONFLICT DO NOTHING;
-- rear_delts
INSERT INTO muscle_development VALUES ('rear_delts', '["posterior_deltoid"]', 'lengthened', 10, 18, 3, '12-20 isolation, 8-12 compound', 'The posterior deltoid is a small muscle that responds to higher relative volume and frequency; reverse-fly horizontal abduction patterns isolate it best, while rows and pull-ups recruit it as a secondary mover. Lead with the stretched horizontal-adduction start of a reverse fly. Three sessions spreads the high weekly set count without excess per-session fatigue.', 'Rabello 2022', 'https://consensus.app/papers/details/e6b30a275c1d5885ae80e58066fe8f9e/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Rear Delt Fly (Cable)', 'rear_delts', 'posterior_deltoid', 'lengthened', 12, 18, 'high', 'Cable reverse fly loads the posterior deltoid from a horizontally adducted stretched start through full horizontal abduction with constant tension; horizontal abduction is the posterior deltoid primary action.', 'Rabello 2022', 'https://consensus.app/papers/details/e6b30a275c1d5885ae80e58066fe8f9e/'),
  ('Rear Delt Reverse Fly (Dumbbell)', 'rear_delts', 'posterior_deltoid', 'lengthened', 12, 20, 'high', 'The reverse peck-deck and dumbbell reverse fly produced greater posterior deltoid activation than seated row or lat pulldown, making it the preferred isolation for the rear delt.', 'Franke 2015', 'https://consensus.app/papers/details/ab93e0552cc854ff9b69ae274a7f4e67/'),
  ('Rear Delt Fly (Dumbbell)', 'rear_delts', 'posterior_deltoid', 'lengthened', 12, 20, 'high', 'Dumbbell reverse fly directly targets the posterior deltoid via horizontal abduction; matched-load comparisons confirm it as a primary posterior-deltoid exercise.', 'Bergquist 2018', 'https://consensus.app/papers/details/1f7d6461249d517999c643fa0c9bfc95/'),
  ('Rear Delt Reverse Fly (Cable)', 'rear_delts', 'posterior_deltoid', 'mid', 12, 18, 'high', 'Cable variation keeps the posterior deltoid loaded through its mid-range arc; cable tension sustains activation where free-weight tension drops off at the top.', 'Bergquist 2018', 'https://consensus.app/papers/details/1f7d6461249d517999c643fa0c9bfc95/'),
  ('Face Pull', 'rear_delts', 'posterior_deltoid', 'mid', 12, 20, 'high', 'Face pulls combine horizontal abduction with external rotation, recruiting the posterior deltoid alongside the mid traps in a high-rep isolation pattern suited to its small size.', 'Rabello 2022', 'https://consensus.app/papers/details/e6b30a275c1d5885ae80e58066fe8f9e/'),
  ('Bent Over Row (Dumbbell)', 'rear_delts', 'posterior_deltoid', 'mid', 8, 12, 'moderate', 'Rowing recruits the posterior deltoid as a secondary mover during the pulling phase; pull-type compounds rank high for posterior deltoid activation and add weekly volume.', 'Rabello 2022', 'https://consensus.app/papers/details/e6b30a275c1d5885ae80e58066fe8f9e/')
ON CONFLICT DO NOTHING;
-- side_delts
INSERT INTO muscle_development VALUES ('side_delts', '["lateral_deltoid"]', 'lengthened', 12, 22, 2, '8-20 reps, lateral raises high-rep friendly, presses lower', 'Lateral deltoid thickness increased 3.3-4.6 pct over 8 weeks with two weekly sessions; lateral raise and shoulder press elicit the highest medial deltoid activation, so combine an isolation lengthened-bias raise with a pressing driver and accept diminishing returns past moderate weekly volume', 'Larsen 2025', 'https://consensus.app/papers/details/ad5d97dc7a015ca78e5f534a699fbcb7/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Lateral Raise (Cable)', 'side_delts', 'lateral_deltoid', 'lengthened', 12, 20, 'high', 'Cable keeps tension on the medial deltoid through the bottom where the dumbbell offloads; matched-ROM 8-week trial found cable and dumbbell raises equally hypertrophic, so cable is the lengthened-bias pick', 'Larsen 2025', 'https://consensus.app/papers/details/ad5d97dc7a015ca78e5f534a699fbcb7/'),
  ('Lateral Raise (Dumbbell)', 'side_delts', 'lateral_deltoid', 'shortened', 10, 20, 'high', 'Lateral raise produced the highest medial deltoid activation (30.3 pct MVIC) of common shoulder exercises; peak tension sits near the top so it biases the shortened position', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/'),
  ('Overhead Press (Dumbbell)', 'side_delts', 'lateral_deltoid', 'mid', 6, 12, 'moderate', 'Shoulder press elicited high medial deltoid activation (27.9 pct MVIC) and serves as a loaded compound driver alongside isolation raises', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/'),
  ('Arnold Press (Dumbbell)', 'side_delts', 'lateral_deltoid', 'mid', 8, 12, 'moderate', 'Pressing variation recruiting medial deltoid at high MVIC comparable to the standard shoulder press, adding a compound stimulus to the side delt', 'Campos 2020', 'https://consensus.app/papers/details/13414fed23555102b8a4992c8783f97b/'),
  ('Upright Row (Barbell)', 'side_delts', 'lateral_deltoid', 'shortened', 10, 15, 'moderate', 'Upright row activates the medial deltoid at 85 pct MVC while also loading traps; useful as a secondary side-delt and trap movement but shortened-biased and less joint-friendly', 'Andersen 2008', 'https://consensus.app/papers/details/6b53630aa61e5e50a65613f1411f6a0d/')
ON CONFLICT DO NOTHING;
-- traps
INSERT INTO muscle_development VALUES ('traps', '["upper_traps","mid_traps","lower_traps"]', 'lengthened', 10, 20, 2, '8-15 reps shrugs and rows, full depression at the bottom for lengthened load', 'Shrugs reach 102 pct MVC of the trapezius and full scapular depression loads the upper traps in the stretched position; mid and lower fibers need horizontal rows and prone raises since shrugs and upright rows under-recruit them, so spread volume across all three regions', 'Andersen 2008', 'https://consensus.app/papers/details/6b53630aa61e5e50a65613f1411f6a0d/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Barbell Shrug', 'traps', 'upper_traps', 'lengthened', 8, 15, 'high', 'Shrug produced the highest trapezius activation of tested exercises at 102 pct MVC and tolerates the heaviest load; a full depression at the bottom places the upper traps under stretch', 'Andersen 2008', 'https://consensus.app/papers/details/6b53630aa61e5e50a65613f1411f6a0d/'),
  ('Dumbbell Shrug', 'traps', 'upper_traps', 'lengthened', 10, 15, 'high', 'Dumbbell loading mirrors the high upper-trap activation of barbell shrugs while allowing a deeper depression at the bottom for a lengthened stimulus', 'Andersen 2008', 'https://consensus.app/papers/details/6b53630aa61e5e50a65613f1411f6a0d/'),
  ('Deadlift (Barbell)', 'traps', 'upper_traps', 'mid', 3, 8, 'high', 'Heavy holds drive upper-trap activity isometrically; trapezius recruitment rises with load during heavy pulls, making the deadlift a high-load upper-trap stimulus via isometric scapular fixation', 'Nagao 2019', 'https://consensus.app/papers/details/26066b09a7ec559e8c97eda76b620e4d/'),
  ('Upright Row (Barbell)', 'traps', 'upper_traps', 'shortened', 10, 15, 'moderate', 'Upright row activates the trapezius at 85 pct MVC at lighter loads than shrugs, hitting the upper traps in the elevated shortened position', 'Andersen 2008', 'https://consensus.app/papers/details/6b53630aa61e5e50a65613f1411f6a0d/'),
  ('Face Pull', 'traps', 'mid_traps', 'mid', 12, 20, 'moderate', 'Prone-row and posterior-fly style horizontal pulls generate the highest lower and middle trapezius activation while minimizing upper-trap dominance, the region shrugs neglect', 'Arlotta 2011', 'https://consensus.app/papers/details/feb355bb95275d80967f13dea67d039f/')
ON CONFLICT DO NOTHING;
-- forearms (CATALOG GAP: no wrist flexion/extension/deviation movements available)
INSERT INTO muscle_development VALUES ('forearms', '["brachioradialis"]', 'lengthened', 6, 12, 2, '10-20 reps; CATALOG GAP - direct wrist flexion and extension and ulnar deviation work is needed but currently missing, only cross-mapped brachioradialis loading is available', 'Forearm muscle size responds to direct loading: isometric ulnar deviation training produced large hypertrophy (g=2.22) of the wrist flexors, so wrist-specific flexion, extension, and deviation movements are required for true forearm development and are absent from the catalog; the wrist extensors in particular stay highly active across grip tasks and need dedicated work', 'Yagiz 2022', 'https://consensus.app/papers/details/589e28c8184850f89b1c654915fc6ba2/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES ('Hammer Curl (Dumbbell)', 'forearms', 'brachioradialis', 'mid', 8, 15, 'moderate', 'Neutral-grip elbow flexion loads the brachioradialis as a forearm flexor; low-load forearm flexion-extension training drove meaningful elbow-flexor and forearm hypertrophy, but this only covers brachioradialis and leaves wrist flexors and extensors untrained', 'Yagiz 2022', 'https://consensus.app/papers/details/589e28c8184850f89b1c654915fc6ba2/') ON CONFLICT DO NOTHING;
-- quads
INSERT INTO muscle_development VALUES ('quads', '["rectus_femoris","vastus_lateralis","vastus_medialis","vastus_intermedius"]', 'lengthened', 12, 18, 2, '6-15 reps; compounds 6-12, isolation 8-15', 'Deep full-ROM squats and leg press at long muscle length drive greater knee-extensor growth than partials in the shortened range; vastii respond strongly to full squats while rectus femoris benefits from hip-extended positions and isolation. Training at longer muscle lengths is favored for quadriceps hypertrophy.', 'Kassiano 2023', 'https://consensus.app/papers/details/d1fe6d13dc165a4f83ea5ec8c91829db/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Squat (Barbell)', 'quads', 'vastii', 'lengthened', 6, 10, 'high', 'Full-depth squat loads the knee extensors at long muscle length; full-ROM squat training drives knee-extensor volume gains and is a primary vastii builder, with depth beyond 90 degrees offering little extra growth.', 'Kubo 2019', 'https://consensus.app/papers/details/31ecf7a95b1c584da565dc9013c1f864/'),
  ('Hack Squat (Machine)', 'quads', 'vastii', 'lengthened', 8, 12, 'high', 'Machine-guided deep squat pattern emphasizes the vastii through a long-length stretched position; full ROM at longer muscle lengths is favored for quadriceps hypertrophy.', 'Kassiano 2023', 'https://consensus.app/papers/details/d1fe6d13dc165a4f83ea5ec8c91829db/'),
  ('Leg Press (Machine)', 'quads', 'vastii', 'lengthened', 8, 12, 'high', 'Deep-range leg press trains the vastii at long muscle length; multi-joint pressing favors vastus lateralis development relative to single-joint work.', 'Burke 2024', 'https://consensus.app/papers/details/0353c3d8c76d55a3b4bde9089885c9b1/'),
  ('Bulgarian Split Squat (Dumbbell)', 'quads', 'vastii', 'lengthened', 8, 12, 'high', 'Unilateral deep split squat loads the quads through a long-length range; full-ROM squatting patterns at longer muscle lengths optimize knee-extensor hypertrophy.', 'Kassiano 2023', 'https://consensus.app/papers/details/d1fe6d13dc165a4f83ea5ec8c91829db/'),
  ('Front Squat (Barbell)', 'quads', 'vastii', 'lengthened', 6, 10, 'high', 'Upright torso squat keeps continuous tension on the knee extensors through deep flexion; full squat training increases knee-extensor muscle volume.', 'Kubo 2019', 'https://consensus.app/papers/details/31ecf7a95b1c584da565dc9013c1f864/'),
  ('Leg Extension (Machine)', 'quads', 'rectus_femoris', 'mid', 10, 15, 'moderate', 'Single-joint knee extension isolates the quadriceps and favors rectus femoris development relative to multi-joint exercises; useful to add rectus femoris stimulus not maximized by squats.', 'Burke 2024', 'https://consensus.app/papers/details/0353c3d8c76d55a3b4bde9089885c9b1/')
ON CONFLICT DO NOTHING;
-- hamstrings
INSERT INTO muscle_development VALUES ('hamstrings', '["hip_extension","knee_flexion","biceps_femoris","semitendinosus"]', 'lengthened', 10, 16, 2, '6-15 reps; hip-hinge 6-12, leg curl/Nordic 8-15', 'Hamstrings show strong lengthened-position effects: eccentric long-length hip-hinge work (RDL, stiff-leg deadlift) and knee-flexion work (Nordic) both drive volume gains. Both functions must be trained, as hip-extension and knee-flexion exercises preferentially grow different hamstring heads.', 'Carmichael 2022', 'https://consensus.app/papers/details/741e073906a65788a7b4d8ad969206be/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Romanian Deadlift (Barbell)', 'hamstrings', 'hip_extension', 'lengthened', 6, 10, 'high', 'Hip-hinge loads the hamstrings at long muscle length under eccentric tension; eccentrically biased RDL increases hamstring cross-sectional area and lengthens biceps femoris fascicles comparably to Nordic work.', 'Crawford 2025', 'https://consensus.app/papers/details/92473b438a4e5b4587b116c1adc95763/'),
  ('Single Leg Romanian Deadlift (Dumbbell)', 'hamstrings', 'hip_extension', 'lengthened', 8, 12, 'high', 'Unilateral hip hinge trains hamstrings at long length; stiff-leg deadlift style hip extension preferentially hypertrophies semimembranosus.', 'Morin 2025', 'https://consensus.app/papers/details/ce21a7f76f3d5745b284bf0b434ecfc1/'),
  ('Good Morning (Barbell)', 'hamstrings', 'hip_extension', 'lengthened', 6, 10, 'moderate', 'Hip-hinge pattern places the hamstrings under load at a stretched long-length position; eccentric long-length hip extension drives biceps femoris and semimembranosus volume.', 'Carmichael 2022', 'https://consensus.app/papers/details/741e073906a65788a7b4d8ad969206be/'),
  ('Nordic Curl', 'hamstrings', 'knee_flexion', 'lengthened', 6, 10, 'high', 'Eccentric knee-flexion at long length selectively hypertrophies semitendinosus and lengthens biceps femoris fascicles; a primary knee-flexion builder.', 'Morin 2025', 'https://consensus.app/papers/details/ce21a7f76f3d5745b284bf0b434ecfc1/'),
  ('Leg Curl (Machine)', 'hamstrings', 'knee_flexion', 'mid', 8, 15, 'moderate', 'Isolated knee-flexion trains the hamstrings through the knee-flexion function that hip-hinge work under-trains; complements hip extension for full hamstring development.', 'Carmichael 2022', 'https://consensus.app/papers/details/741e073906a65788a7b4d8ad969206be/')
ON CONFLICT DO NOTHING;
-- calves
INSERT INTO muscle_development VALUES ('calves', '["gastrocnemius","soleus"]', 'lengthened', 12, 20, 3, '8-20 reps; emphasize loaded stretch at the bottom', 'Triceps surae require both standing (knee-extended, gastrocnemius lengthened) and seated (knee-flexed, soleus) work. Training at long muscle lengths and emphasizing the stretched bottom range maximizes gastrocnemius hypertrophy; standing raises beat seated for gastrocnemius while seated work is needed for soleus.', 'Kinoshita 2023', 'https://consensus.app/papers/details/511222726c335316b43f207aa0f8a2c1/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Standing Calf Raise (Dumbbell)', 'calves', 'gastrocnemius', 'lengthened', 10, 15, 'high', 'Knee-extended plantarflexion lengthens the gastrocnemius and produced far greater gastrocnemius and whole triceps surae hypertrophy than seated raises; emphasize the stretched bottom position.', 'Kinoshita 2023', 'https://consensus.app/papers/details/511222726c335316b43f207aa0f8a2c1/'),
  ('Calf Raise (Machine)', 'calves', 'gastrocnemius', 'lengthened', 10, 20, 'high', 'Partial-ROM training emphasizing the initial (lengthened) portion of the excursion elicited greater gastrocnemius growth than full or shortened-range work; load the long-length bottom range.', 'Kassiano 2023b', 'https://consensus.app/papers/details/40f4c30ba9965f7c946f2649a064e5a1/'),
  ('Seated Calf Raise (Machine)', 'calves', 'soleus', 'lengthened', 12, 20, 'high', 'Knee-flexed plantarflexion is required to train the soleus, which responds similarly under seated and standing conditions while the gastrocnemius does not; necessary to cover the bent-knee soleus function.', 'Kinoshita 2023', 'https://consensus.app/papers/details/511222726c335316b43f207aa0f8a2c1/')
ON CONFLICT DO NOTHING;
-- abs
INSERT INTO muscle_development VALUES ('abs', '["rectus_abdominis","obliques"]', 'lengthened', 12, 20, 3, '8-20 reps weighted, full spinal flexion ROM', 'Loaded ab work builds rectus abdominis thickness; leg-raise patterns from a long lying position maximize rectus activation while anti-rotation work targets obliques, and training that emphasizes long muscle lengths is favored for hypertrophy', 'Mandroukas 2022', 'https://consensus.app/papers/details/277c0a22f7e75adea8222506ca6b16cd/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Hanging Leg Raise', 'abs', 'rectus_abdominis', 'lengthened', 10, 15, 'high', 'Leg movements from a long-lying/hanging position produce higher rectus abdominis activation than the external oblique, training the muscle through a long-length lower-ab pattern', 'Mandroukas 2022', 'https://consensus.app/papers/details/277c0a22f7e75adea8222506ca6b16cd/'),
  ('Cable Crunch', 'abs', 'rectus_abdominis', 'lengthened', 10, 15, 'high', 'Loaded full-ROM spinal flexion at long muscle lengths is favored for hypertrophy; weighted crunch patterns increased rectus abdominis thickness and strength', 'Gluppe 2023', 'https://consensus.app/papers/details/9d29b2f24eeb569c9820353b5f9499f4/'),
  ('Crunch (Machine)', 'abs', 'rectus_abdominis', 'mid', 12, 20, 'moderate', 'Curl-up/crunch loading increased rectus abdominis thickness and strength; machine loading allows progressive overload through spinal flexion', 'Gluppe 2023', 'https://consensus.app/papers/details/9d29b2f24eeb569c9820353b5f9499f4/'),
  ('Cable Core Pallof Press', 'abs', 'obliques', 'mid', 10, 15, 'moderate', 'Dynamic trunk movements show dominant external oblique activation; anti-rotation loading targets the obliques specifically', 'Mandroukas 2022', 'https://consensus.app/papers/details/277c0a22f7e75adea8222506ca6b16cd/'),
  ('Pallof Press (Cable)', 'abs', 'obliques', 'mid', 10, 15, 'moderate', 'Anti-rotation pressing biases the external oblique, which dominates during dynamic rotational and anti-rotational trunk loading', 'Mandroukas 2022', 'https://consensus.app/papers/details/277c0a22f7e75adea8222506ca6b16cd/')
ON CONFLICT DO NOTHING;
-- adductors (CATALOG GAP: no adductor-isolation movement; trained as synergist in deep compounds)
INSERT INTO muscle_development VALUES ('adductors', '["adductors"]', 'lengthened', 6, 10, 2, '6-12 reps, deep/full hip flexion', 'Full-depth squatting drove significantly greater adductor muscle volume growth than half squats, and squat training produced clear adductor cross-sectional area gains; adductors are loaded at long length under deep hip flexion, with no isolation exercise available in the catalog', 'Kubo 2019', 'https://consensus.app/papers/details/31ecf7a95b1c584da565dc9013c1f864/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Squat (Barbell)', 'adductors', 'adductors', 'lengthened', 6, 10, 'high', 'Full squat training increased adductor muscle volume significantly more than half squats, and back squat training produced clear adductor cross-sectional area growth; deep hip flexion loads the adductors at long length', 'Kubo 2019', 'https://consensus.app/papers/details/31ecf7a95b1c584da565dc9013c1f864/'),
  ('Leg Press (Machine)', 'adductors', 'adductors', 'lengthened', 8, 12, 'moderate', 'Deep-ROM closed-chain knee/hip extension under load mirrors the squat stimulus that grew adductor volume; greater depth places the adductors under longer-length tension', 'Kubo 2019', 'https://consensus.app/papers/details/31ecf7a95b1c584da565dc9013c1f864/'),
  ('Bulgarian Split Squat (Dumbbell)', 'adductors', 'adductors', 'lengthened', 8, 12, 'moderate', 'Squat-pattern training elicits adductor hypertrophy; a deep split-stance position drives the rear-leg hip into long-length flexion, loading the adductors', 'Plotkin 2023', 'https://consensus.app/papers/details/7e990ce959d45b929c847edd64924a97/'),
  ('Lunge (Barbell)', 'adductors', 'adductors', 'lengthened', 8, 12, 'moderate', 'Squat-type loading produced clear adductor cross-sectional area gains; a deep lunge step lengthens the lead-leg adductors under load', 'Plotkin 2023', 'https://consensus.app/papers/details/7e990ce959d45b929c847edd64924a97/')
ON CONFLICT DO NOTHING;
-- lower_back (trained largely as a synergist; do NOT prescribe to failure)
INSERT INTO muscle_development VALUES ('lower_back', '["erector_spinae"]', 'mid', 4, 8, 2, '6-12 reps, controlled, avoid failure', 'Free-weight hip hinges (deadlifts, good mornings, RDLs) significantly activate the lumbar erector spinae but train them largely as a synergist; erector activation rises as the torso angle becomes more horizontal, so moderate non-failure volume is appropriate', 'Steele 2013', 'https://consensus.app/papers/details/91086725614f5d6f9d2aa715412f5999/') ON CONFLICT DO NOTHING;
INSERT INTO exercise_science VALUES
  ('Deadlift (Barbell)', 'lower_back', 'erector_spinae', 'mid', 6, 10, 'moderate', 'Deadlift hip-hinge variations produce high lumbar erector spinae activation; erector EMG was highest in the most horizontal-torso starting positions and declined as knee flexion increased', 'Rivera 2021', 'https://consensus.app/papers/details/78059dfc9cc35155b3d43bdf10c4826e/'),
  ('Romanian Deadlift (Barbell)', 'lower_back', 'erector_spinae', 'mid', 8, 12, 'moderate', 'A more horizontal RDL-style torso angle elicited the highest erector spinae activation among hip-hinge deadlift variations, training the lumbar extensors through a hip-dominant pattern', 'Rivera 2021', 'https://consensus.app/papers/details/78059dfc9cc35155b3d43bdf10c4826e/'),
  ('Good Morning (Barbell)', 'lower_back', 'erector_spinae', 'mid', 8, 12, 'moderate', 'The good morning significantly activates the erector spinae during concentric hip extension, but as a compound hip hinge it conditions the lumbar extensors largely as a synergist', 'Ju 2025', 'https://consensus.app/papers/details/b00a69e4f183555d9d1c5401ef5bbae6/')
ON CONFLICT DO NOTHING;
