-- 0080: repair the machine/chin classifier collision, curate the movements the
-- selector could not see, and re-ground every citation on a real vault note.
--
-- NOTE ON SHAPE: exercise_science is a VIEW over exercise_muscle (the rows whose
-- citation IS NOT NULL) -- curating a movement means filling the science columns
-- on its existing exercise_muscle row, NOT inserting into the view. Writing to
-- the view fails outright, and a DELETE+INSERT on exercise_muscle would silently
-- destroy any science already curated there. Both are avoided below.
--
-- 1. CLASSIFIER. classify_exercise tested "chin" as a bare substring, which also
--    matches ma-CHIN-e. Seven exercises / 2,155 logged sets were classified as
--    chin-ups: Ab Crunch Machine (744 sets) credited to lats instead of abs, and
--    five overhead-press variants (1,402 sets) credited as PULLING -- which also
--    reset the pull rest-gate clock on a push day, the exact class of miscue
--    ENGINE_INVARIANTS #4 exists to prevent. Fixed in code with a word-boundary
--    helper; the stored rows are repaired here. The DELETE is guarded on
--    citation IS NULL so it can never drop a curated row.
--
-- 2. CURATION. The engine could not select these movements at all -- no science
--    row means never a candidate, never credits a head, never competes for a
--    slot -- despite tens of thousands of logged sets. 59 rows are UPDATEs onto
--    an existing (exercise, muscle) pair; 5 are INSERTs for movements with no
--    muscle row at all. 4 curated rows were deliberately NOT applied because
--    they would CHANGE muscle attribution rather than annotate it (both upright
--    rows traps->front_delts, both sumo squats +adductors). Those are training
--    decisions, not curation, and are left for an explicit call.
--
-- 3. CITATIONS. 113 of 126 curated rows cited a paper appearing nowhere in the
--    vault, against the planner's own rule to cite only real catalogue notes.
--    80 are re-grounded on notes whose CONTENT was read and confirmed to support
--    the specific claim. 33 could not be and are MARKED 'UNGROUNDED: ...' rather
--    than given a citation that would look real and not be -- the row stays
--    usable, the provenance gap stays greppable.
--
-- Every citation written here was verified verbatim against the 804-note vault.

-- ── 1. classifier repair ────────────────────────────────────────────────────
DELETE FROM exercise_muscle WHERE exercise_name = 'Machine Shoulder Press' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Shoulder Press', 'front_delts', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Shoulder Press' AND muscle='front_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Shoulder Press', 'side_delts', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Shoulder Press' AND muscle='side_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Shoulder Press', 'triceps', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Shoulder Press' AND muscle='triceps');
DELETE FROM exercise_muscle WHERE exercise_name = 'Seated Shoulder Press (Machine)' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Seated Shoulder Press (Machine)', 'front_delts', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Seated Shoulder Press (Machine)' AND muscle='front_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Seated Shoulder Press (Machine)', 'side_delts', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Seated Shoulder Press (Machine)' AND muscle='side_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Seated Shoulder Press (Machine)', 'triceps', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Seated Shoulder Press (Machine)' AND muscle='triceps');
DELETE FROM exercise_muscle WHERE exercise_name = 'Machine Overhead Press' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Overhead Press', 'front_delts', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Overhead Press' AND muscle='front_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Overhead Press', 'side_delts', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Overhead Press' AND muscle='side_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Machine Overhead Press', 'triceps', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Machine Overhead Press' AND muscle='triceps');
DELETE FROM exercise_muscle WHERE exercise_name = 'Overhead Press (Smith Machine)' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Overhead Press (Smith Machine)', 'front_delts', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Overhead Press (Smith Machine)' AND muscle='front_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Overhead Press (Smith Machine)', 'side_delts', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Overhead Press (Smith Machine)' AND muscle='side_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Overhead Press (Smith Machine)', 'triceps', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Overhead Press (Smith Machine)' AND muscle='triceps');
DELETE FROM exercise_muscle WHERE exercise_name = 'Smith Machine Overhead Shoulder Press' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Smith Machine Overhead Shoulder Press', 'front_delts', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Smith Machine Overhead Shoulder Press' AND muscle='front_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Smith Machine Overhead Shoulder Press', 'side_delts', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Smith Machine Overhead Shoulder Press' AND muscle='side_delts');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Smith Machine Overhead Shoulder Press', 'triceps', 'secondary', 0.5 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Smith Machine Overhead Shoulder Press' AND muscle='triceps');
DELETE FROM exercise_muscle WHERE exercise_name = 'Ab Crunch Machine' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Ab Crunch Machine', 'abs', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Ab Crunch Machine' AND muscle='abs');
DELETE FROM exercise_muscle WHERE exercise_name = 'Crunch (Machine)' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit) SELECT 'Crunch (Machine)', 'abs', 'primary', 1.0 WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Crunch (Machine)' AND muscle='abs');

-- ── 2a. curate existing rows (59) ──────────────────────────────────────────
UPDATE exercise_muscle SET region='long_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The long head is biarticular and reaches its optimal length-tension only when the shoulder is flexed, so both readings of this movement (overhead extension and lying extension) load it at length -- Stasinaki recorded 15 pct vs 10 pct thickness for overhead versus pushdown, and Wakahara''s MRI put lying triceps extension''s growth in the proximal (long-head) region.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Tricep Extension' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='long_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='Pressing from behind the head keeps the humerus overhead, which elongates the long head at the shoulder while it works at the elbow -- the passive-tension case the vault singles out as the deliberate way to design a long-head exercise.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Tricep Press' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_head', length_bias='mid', rep_low=8, rep_high=20, sfr_tier='high', rationale='With the humerus held at the side the long head is slackened at the shoulder and the medial and lateral heads take over, making the pushdown the complement to overhead work rather than a substitute for it.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Tricep Pushdown' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_head', length_bias='mid', rep_low=8, rep_high=20, sfr_tier='high', rationale='Read as a rope pushdown (the overhead rope variant is already curated separately), the humerus stays at the side and the medial and lateral heads carry the elbow extension.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Rope Tricep Extension' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='medial_head', length_bias='mid', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='The single-arm reverse-grip pushdown keeps the humerus pinned at the side, the position in which the vault records the medial and lateral heads as most active and the long head as slack.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable One Arm Underhand Tricep Extension' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_head', length_bias='shortened', rep_low=8, rep_high=15, sfr_tier='moderate', rationale='The shoulder sits extended behind the torso, which shortens the long head at the shoulder and leaves the medial and lateral heads to drive elbow extension into a fully shortened lockout.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Bench Dip' AND muscle='triceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_head', length_bias='shortened', rep_low=12, rep_high=25, sfr_tier='moderate', rationale='Band tension rises as the band lengthens, so resistance peaks at the locked-out (shortened) end rather than at the stretch, and the at-side humerus places the load on the medial and lateral heads.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Mini Loop Band Tricep Press' AND muscle='triceps' AND citation IS NULL;
-- SKIPPED (would change attribution, not annotate it): Dumbbell Upright Row -> front_delts
-- SKIPPED (would change attribution, not annotate it): Cable Upright Row -> front_delts
UPDATE exercise_muscle SET region='mid_chest', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='A flat horizontal press loads the sternal head, and the fixed machine path holds the pecs near mid-length rather than accentuating either end of the range.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammerstrength Chest Press' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='mid_chest', length_bias='lengthened', rep_low=6, rep_high=12, sfr_tier='high', rationale='Flat pressing targets the sternal head, and dumbbells let the humeri travel below the torso line so the pecs are loaded in the stretched position the vault identifies as the most anabolic part of the range.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Bench Press' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='mid_chest', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='Flat machine pressing loads the sternal head with a guided path that neither accentuates the stretch nor unloads at lockout the way a barbell does.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Machine Bench Press' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='mid_chest', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The chest fly is the vault''s own worked example of a long-length-accentuated exercise -- peak torque falls where the sternal head is maximally stretched.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Fly' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='upper_chest', length_bias='lengthened', rep_low=6, rep_high=12, sfr_tier='high', rationale='A 30-45 degree incline shifts the line of pull onto the clavicular head, and the dumbbell path allows a deep bottom position that loads it at long length.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Incline Bench Press' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='upper_chest', length_bias='lengthened', rep_low=6, rep_high=12, sfr_tier='high', rationale='A 30-45 degree incline shifts the line of pull onto the clavicular head, and the dumbbell path allows a deep bottom position that loads it at long length.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Incline Bench Press (Dumbbell)' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='lower_chest', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='The vault groups decline pressing with flat pressing under the sternal head, and the declined torso angle biases the lower sternal fibers whose line of pull matches the descending push.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammerstrength Decline Chest Press' AND muscle='chest' AND citation IS NULL;
UPDATE exercise_muscle SET region='mid_chest', length_bias='shortened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='Bands add tension at the top of the range where free weights unload, which inverts the fly''s usual stretch bias and concentrates load in the fully adducted, shortened position.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Handle Band Pec Fly' AND muscle='chest' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit, region, length_bias, rep_low, rep_high, sfr_tier, rationale, citation) SELECT 'Push Up', 'chest', 'primary', 1.0, 'mid_chest', 'mid', 8, 20, 'moderate', 'The push-up is a horizontal push, whose primary muscles are the chest with the anterior delts, but the closed-chain bodyweight load caps how much mechanical tension it can deliver to a trained lifter.', 'helms-2018-lv4-exercise-selection.md' WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Push Up' AND muscle='chest');
UPDATE exercise_muscle SET region='lats', length_bias='lengthened', rep_low=6, rep_high=15, sfr_tier='high', rationale='Frontal-plane humeral adduction from an overhead start is what maximally activates the lats, and the overhead position is where the lat is under greatest stretch.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='V-Bar Pulldown' AND muscle='lats' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit, region, length_bias, rep_low, rep_high, sfr_tier, rationale, citation) SELECT 'Lat Pulldown', 'lats', 'primary', 1.0, 'lats', 'lengthened', 6, 15, 'high', 'The vault names the lat pulldown alongside the pull-up as maximally activating the lats via frontal-plane humeral adduction, loaded from the stretched overhead position.', 'schoenfeld-2021-ch8-program-design.md' WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Lat Pulldown' AND muscle='lats');
UPDATE exercise_muscle SET region='lats', length_bias='lengthened', rep_low=6, rep_high=15, sfr_tier='high', rationale='Grip width has only a minor effect on lat activation, with shoulder-width to twice-shoulder-width covering the spectrum, so the wide grip is a lat pulldown loaded at overhead stretch like any other.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Wide Grip Lat Pulldown' AND muscle='lats' AND citation IS NULL;
UPDATE exercise_muscle SET region='lats', length_bias='lengthened', rep_low=6, rep_high=15, sfr_tier='moderate', rationale='Still a vertical pull loading the lats from the stretched overhead position, but the vault records the pronated grip as the maximal-lat variant, so the supinated version is a complement rather than a replacement.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Reverse Grip Pull Down' AND muscle='lats' AND citation IS NULL;
UPDATE exercise_muscle SET region='lats', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='Row variations are a horizontal pull, whose primary muscles are the lats and scapular retractors, with the humerus travelling through mid-range rather than an accentuated stretch.', citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Dumbbell Row' AND muscle='lats' AND citation IS NULL;
UPDATE exercise_muscle SET region='lats', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='A machine horizontal pull loading the lats and scapular retractors, with the fixed path holding the lat near mid-length through the stroke.', citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Hammerstrength High Row' AND muscle='lats' AND citation IS NULL;
UPDATE exercise_muscle SET region='lats', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='Unilateral machine rowing is a horizontal pull with the lats primary, and the independent arms let each side reach full excursion without the stronger side compensating.', citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Hammerstrength Iso Row' AND muscle='lats' AND citation IS NULL;
UPDATE exercise_muscle SET region='mid_traps', length_bias='mid', rep_low=6, rep_high=15, sfr_tier='high', rationale='The vault assigns midback traps and rhomboids to sagittal-plane rows and names the seated row specifically, with scapular retraction working through mid-range.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Cable Row - Bar Grip' AND muscle='mid_back' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='The shoulder press loads primarily the anterior head, because the external rotation of the shoulder during the press places that head in direct opposition to gravity.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Shoulder Press' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='The shoulder press loads primarily the anterior head, because the external rotation of the shoulder during the press places that head in direct opposition to gravity.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Shoulder Press (Dumbbell)' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='Overhead pressing on a fixed path loads primarily the anterior head, since the externally rotated shoulder puts that head in direct opposition to gravity.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Machine Shoulder Press' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='Overhead pressing on a fixed path loads primarily the anterior head, since the externally rotated shoulder puts that head in direct opposition to gravity.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Shoulder Press (Machine)' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=6, rep_high=12, sfr_tier='high', rationale='Overhead pressing on a fixed path loads primarily the anterior head, since the externally rotated shoulder puts that head in direct opposition to gravity.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Machine Overhead Press' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='anterior_deltoid', length_bias='mid', rep_low=8, rep_high=20, sfr_tier='moderate', rationale='The vault maps the three deltoid heads to three planes and assigns the anterior head to sagittal-plane work, naming the front raise as its exercise.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Front Raise' AND muscle='front_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_deltoid', length_bias='shortened', rep_low=8, rep_high=20, sfr_tier='high', rationale='The middle head is the frontal-plane abductor and needs internal shoulder rotation (pinky slightly up) to oppose gravity directly, with resistance torque peaking near horizontal where the head is already shortened.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Lateral Raise' AND muscle='side_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='lateral_deltoid', length_bias='shortened', rep_low=12, rep_high=25, sfr_tier='moderate', rationale='Frontal-plane abduction targets the middle head, and band tension rising with elongation stacks the load even further toward the top of the raise where the head is shortened.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Handle Band Lateral Raise' AND muscle='side_delts' AND citation IS NULL;
UPDATE exercise_muscle SET region='biceps_brachii', length_bias='mid', rep_low=8, rep_high=20, sfr_tier='high', rationale='A supinated grip with the humerus hanging at the side targets all the elbow flexors without biasing either head -- the long head needs the humerus behind the body and the short head needs it abducted.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dumbbell Bicep Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='biceps_brachii', length_bias='mid', rep_low=8, rep_high=15, sfr_tier='high', rationale='A supinated grip with the humerus at the side targets all the elbow flexors evenly; neither head is placed in the position the vault identifies as its own.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Barbell Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='biceps_brachii', length_bias='shortened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='Supinated curling loads all the elbow flexors, but band tension climbs as the band lengthens so peak resistance lands at full elbow flexion rather than at the stretch.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Handle Band Bicep Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='biceps_brachii', length_bias='shortened', rep_low=12, rep_high=25, sfr_tier='moderate', rationale='A supinated curl against a loop band puts maximum resistance at the top of the flexion where the band is most stretched, so the stimulus sits at short muscle length.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Mini Loop Band Kneeling Bicep Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='short_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The preacher angle abducts and flexes the humerus, which is where the short head is maximally active and the long head is actively insufficient, and peak torque falls at the extended bottom where that short head is stretched.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Machine Preacher Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='short_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The preacher angle abducts and flexes the humerus, which is where the short head is maximally active and the long head is actively insufficient, and peak torque falls at the extended bottom where that short head is stretched.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Preacher Curl (Machine)' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='long_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The incline drops the humerus behind the body, the exact position in which the vault records the long head as maximally active and stretched across both the shoulder and the elbow.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Incline Hammer Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='long_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The vault names the cable curl with the elbow behind the torso as the long-head exercise -- the humerus behind the body stretches the long head across the shoulder while it works at the elbow.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Behind the Back Cable Bicep Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='long_head', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The defining feature of the drag curl is driving the elbows back behind the torso, which is the humerus-behind-body position the vault ties to maximal long-head activation.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Barbell Bicep Drag Curl' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='brachialis', length_bias='mid', rep_low=8, rep_high=20, sfr_tier='high', rationale='A neutral grip shifts work off the supinating biceps onto the deeper elbow flexors -- the vault assigns the neutral hammer grip to the brachioradialis and the pronated grip to the brachialis and brachioradialis.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Rope Hammer Curls' AND muscle='biceps' AND citation IS NULL;
UPDATE exercise_muscle SET region='rectus_abdominis', length_bias='shortened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='Standard crunch variations produce spinal flexion, which the vault assigns to the upper rectus abdominis and which loads it into its shortened position.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Crunches' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='rectus_abdominis', length_bias='shortened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='Standard crunch variations produce spinal flexion, which the vault assigns to the upper rectus abdominis and which loads it into its shortened position.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Crunch' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='rectus_abdominis', length_bias='lengthened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='The vault prescribes hanging leg raises for the rectus abdominis and contraindicates straight-leg sit-ups because those are iliopsoas-dominated and raise disc pressure; the hanging start also begins with the trunk extended and the rectus at length.', citation='injury-prevention-lumbar.md' WHERE exercise_name='Vertical Knee Raise' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='obliques', length_bias='mid', rep_low=10, rep_high=20, sfr_tier='high', rationale='The vault names the cable woodchop as an oblique exercise, since the obliques require rotation and lateral flexion loading that spinal-flexion work does not supply.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Wood Chop' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='obliques', length_bias='mid', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='Loaded trunk rotation is the movement category the vault assigns to the obliques, which crunches and leg raises leave untrained.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Landmine Core Rotation' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='obliques', length_bias='mid', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='The vault lists trunk rotations as the training method for the obliques and internal abdominis, which it identifies as the primary generators of the intra-abdominal pressure that protects the lumbar spine.', citation='injury-prevention-lumbar.md' WHERE exercise_name='Loop Band Standing Ab Twist' AND muscle='abs' AND citation IS NULL;
UPDATE exercise_muscle SET region='obliques', length_bias='mid', rep_low=12, rep_high=25, sfr_tier='moderate', rationale='Seated loaded rotation trains the obliques and internal abdominis, the muscles the vault credits with generating intra-abdominal pressure, though the light implement caps the tension available.', citation='injury-prevention-lumbar.md' WHERE exercise_name='Medicine Ball Russian Twist' AND muscle='abs' AND citation IS NULL;
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit, region, length_bias, rep_low, rep_high, sfr_tier, rationale, citation) SELECT 'Leg Extension', 'quads', 'primary', 1.0, 'rectus_femoris', 'shortened', 8, 20, 'high', 'Open-chain knee extension maximally activates the rectus femoris -- the head that squat-only training failed to grow in Fonseca -- and the vault classifies leg extension at end range as short-length accentuated.', 'schoenfeld-2021-ch8-program-design.md' WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Leg Extension' AND muscle='quads');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit, region, length_bias, rep_low, rep_high, sfr_tier, rationale, citation) SELECT 'Leg Press', 'quads', 'primary', 1.0, 'vastii', 'lengthened', 6, 12, 'high', 'Multi-joint pressing maximally activates the vasti, and a deep bottom position loads them at long knee flexion angles where the vault records growth at every measured site.', 'schoenfeld-2021-ch8-program-design.md' WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Leg Press' AND muscle='quads');
INSERT INTO exercise_muscle (exercise_name, muscle, role, credit, region, length_bias, rep_low, rep_high, sfr_tier, rationale, citation) SELECT 'Hack Squat', 'quads', 'primary', 1.0, 'vastii', 'lengthened', 6, 12, 'high', 'The vault classes the hack squat as a lower machine compound at 6-12 reps and RPE 6-9, and the guided deep bottom loads the vasti at long muscle length without the balance demand of a free squat.', 'helms-2018-qsg-program-building.md' WHERE NOT EXISTS (SELECT 1 FROM exercise_muscle WHERE exercise_name='Hack Squat' AND muscle='quads');
UPDATE exercise_muscle SET region='vastii', length_bias='lengthened', rep_low=6, rep_high=12, sfr_tier='moderate', rationale='Fonseca found the Smith squat alone failed to significantly develop the vastus medialis and rectus femoris, so it is a vasti loader that must be paired with knee extension rather than a complete quad exercise.', citation='exercise-selection-hypertrophy.md' WHERE exercise_name='Smith Machine Squat' AND muscle='quads' AND citation IS NULL;
UPDATE exercise_muscle SET region='vastii', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='moderate', rationale='A wide-stance squat is a multi-joint knee-extension pattern loading the vasti through a deep bottom, and the vault records stances at or beyond 140 pct shoulder width as increasing glute max contribution alongside it.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Kettlebell Sumo Squat' AND muscle='quads' AND citation IS NULL;
UPDATE exercise_muscle SET region='vastii', length_bias='lengthened', rep_low=8, rep_high=15, sfr_tier='moderate', rationale='A wide-stance squat is a multi-joint knee-extension pattern loading the vasti through a deep bottom, and the vault records stances at or beyond 140 pct shoulder width as increasing glute max contribution alongside it.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Sumo Squat (Kettlebell)' AND muscle='quads' AND citation IS NULL;
UPDATE exercise_muscle SET region='vastii', length_bias='lengthened', rep_low=15, rep_high=30, sfr_tier='low', rationale='The squat pattern loads the vasti at long knee flexion angles, but bodyweight alone sits at or below the roughly 30 pct 1RM minimum effective loading threshold for a trained lifter, so this functions as preparatory volume rather than a growth stimulus.', citation='load-selection-hypertrophy.md' WHERE exercise_name='Air Squats' AND muscle='quads' AND citation IS NULL;
UPDATE exercise_muscle SET region='vastii', length_bias='lengthened', rep_low=15, rep_high=30, sfr_tier='low', rationale='The squat pattern loads the vasti at long knee flexion angles, but bodyweight alone sits at or below the roughly 30 pct 1RM minimum effective loading threshold for a trained lifter, so this functions as preparatory volume rather than a growth stimulus.', citation='load-selection-hypertrophy.md' WHERE exercise_name='Squat (Bodyweight)' AND muscle='quads' AND citation IS NULL;
UPDATE exercise_muscle SET region='vastii', length_bias='shortened', rep_low=15, rep_high=30, sfr_tier='low', rationale='Band resistance peaks at the top of the squat where the band is most stretched and the vasti are shortened, and the achievable band load falls short of the roughly 30 pct 1RM effective threshold.', citation='load-selection-hypertrophy.md' WHERE exercise_name='Handle Band Squat' AND muscle='quads' AND citation IS NULL;
-- SKIPPED (would change attribution, not annotate it): Kettlebell Sumo Squat -> adductors
-- SKIPPED (would change attribution, not annotate it): Sumo Squat (Kettlebell) -> adductors
UPDATE exercise_muscle SET region='knee_flexion', length_bias='shortened', rep_low=8, rep_high=20, sfr_tier='high', rationale='Knee flexion exercises preferentially target the biceps femoris and are required because multi-joint lower-body work produces only about half the hamstring EMG of single-joint work; the prone position leaves the hip extended, so the vault notes the RDL loads the hamstring at stretch better than the lying curl does.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Lying Hamstrings Curl' AND muscle='hamstrings' AND citation IS NULL;
UPDATE exercise_muscle SET region='knee_flexion', length_bias='shortened', rep_low=8, rep_high=20, sfr_tier='high', rationale='Knee flexion exercises preferentially target the biceps femoris and are required because multi-joint lower-body work produces only about half the hamstring EMG of single-joint work; the prone position leaves the hip extended, so the vault notes the RDL loads the hamstring at stretch better than the lying curl does.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Lying Leg Curl (Machine)' AND muscle='hamstrings' AND citation IS NULL;
UPDATE exercise_muscle SET region='knee_flexion', length_bias='shortened', rep_low=8, rep_high=20, sfr_tier='moderate', rationale='Unilateral standing knee flexion trains the biceps femoris through the vault''s required knee-flexion category, but the extended hip leaves the hamstring short at its proximal joint throughout the movement.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Standing Leg Curl' AND muscle='hamstrings' AND citation IS NULL;
UPDATE exercise_muscle SET region='gluteus_maximus', length_bias='shortened', rep_low=8, rep_high=15, sfr_tier='high', rationale='The hip thrust produces the greatest gluteus maximus EMG of the tested exercises with peak torque at the end of hip extension, which is the short-length half of the coverage the vault says the glute max requires.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Barbell Hip Thrust' AND muscle='glutes' AND citation IS NULL;
UPDATE exercise_muscle SET region='gluteus_maximus', length_bias='shortened', rep_low=12, rep_high=25, sfr_tier='moderate', rationale='The thrust pattern puts peak glute max torque at the end of hip extension, and band tension rising with elongation reinforces that shortened-position loading while capping absolute load.', citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Mini Loop Band Glute Thrust' AND muscle='glutes' AND citation IS NULL;
UPDATE exercise_muscle SET region='gluteus_maximus', length_bias='shortened', rep_low=10, rep_high=20, sfr_tier='moderate', rationale='The vault lists kettlebell swings among ballistic stretch-shortening-cycle exercises trained for the eccentric-to-concentric transition, so the elastic recoil and the hip-extension lockout, not sustained tension at length, are what the movement delivers.', citation='stretch-shortening-cycle.md' WHERE exercise_name='Kettlebell Swing' AND muscle='glutes' AND citation IS NULL;

-- ── 3. citation re-grounding (80) ──────────────────────────────────────────
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Dip (Tricep)' AND citation='Alves 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Machine Tricep Dip' AND citation='Alves 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Tricep Pushdown (Cable)' AND citation='Alves 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Triceps Rope Pushdown' AND citation='Alves 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Lat Pulldown - Close Grip (Cable)' AND citation='Asayama 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Pull-Up' AND citation='Asayama 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Rear Delt Fly (Dumbbell)' AND citation='Bergquist 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Rear Delt Reverse Fly (Cable)' AND citation='Bergquist 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Leg Extension (Machine)' AND citation='Burke 2024';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Leg Press (Machine)' AND citation='Burke 2024';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Arnold Press (Dumbbell)' AND citation='Campos 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Front Raise (Dumbbell)' AND citation='Campos 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammerstrength Shoulder Press' AND citation='Campos 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Lateral Raise (Dumbbell)' AND citation='Campos 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Overhead Press (Barbell)' AND citation='Campos 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Good Morning (Barbell)' AND citation='Carmichael 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Leg Curl (Machine)' AND citation='Carmichael 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Leg Curl (Machine)' AND citation='Carmichael 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Decline Bench Press (Barbell)' AND citation='Christian 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Overhead Press (Dumbbell)' AND citation='Coratella 2022';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Romanian Deadlift (Barbell)' AND citation='Crawford 2025';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Bent Over Row (Barbell)' AND citation='Currier 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Bent Over Row (Barbell)' AND citation='Currier 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Row' AND citation='Fennell 2016';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Cable Row - V Grip (Cable)' AND citation='Fennell 2016';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Rear Delt Reverse Fly (Dumbbell)' AND citation='Franke 2015';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Cable Row' AND citation='Franke 2015';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Crunch' AND citation='Gluppe 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Crunch (Machine)' AND citation='Gluppe 2023';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Iso-Lateral Row (Machine)' AND citation='Heaselgrave 2019';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Iso-Lateral Row (Machine)' AND citation='Heaselgrave 2019';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Single Arm Row (Dumbbell)' AND citation='Heaselgrave 2019';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='T-Bar Row' AND citation='Heaselgrave 2019';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Good Morning (Barbell)' AND citation='Ju 2025';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Bulgarian Split Squat (Dumbbell)' AND citation='Kassiano 2023';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Hack Squat (Machine)' AND citation='Kassiano 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Romanian Deadlift (Barbell)' AND citation='Kassiano 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Close Grip Bench Press (Barbell)' AND citation='Kholinne 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Skull Crusher (Barbell)' AND citation='Kholinne 2018';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Seated Calf Raise (Machine)' AND citation='Kinoshita 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Standing Calf Raise (Dumbbell)' AND citation='Kinoshita 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Front Squat (Barbell)' AND citation='Kubo 2019';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Squat (Barbell)' AND citation='Kubo 2019';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Squat (Barbell)' AND citation='Kubo 2019';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Rope Overhead Triceps Extension' AND citation='Maeo 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Overhead Tricep Extension (Cable)' AND citation='Maeo 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Overhead Tricep Extension (Dumbbell)' AND citation='Maeo 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Overhead Triceps Extension (Cable)' AND citation='Maeo 2022';
UPDATE exercise_muscle SET citation='zatsiorsky-2021-ch8-injury-prevention.md' WHERE exercise_name='Hanging Leg Raise' AND citation='Mandroukas 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Bulgarian Split Squat (Dumbbell)' AND citation='McCurdy 2017 / Kassiano 2023';
UPDATE exercise_muscle SET citation='muscle-architecture-strength.md' WHERE exercise_name='Nordic Curl' AND citation='Morin 2025';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Single Leg Romanian Deadlift (Dumbbell)' AND citation='Morin 2025';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Incline Curl (Dumbbell)' AND citation='Oliveira 2009 / Iwane 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Glute Bridge (Barbell)' AND citation='Plotkin 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hip Thrust (Barbell)' AND citation='Plotkin 2023';
UPDATE exercise_muscle SET citation='range-of-motion-hypertrophy.md' WHERE exercise_name='Squat (Barbell)' AND citation='Plotkin 2023 / Barbalho 2020';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Bent Over Row (Dumbbell)' AND citation='Rabello 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Rear Delt Fly (Cable)' AND citation='Rabello 2022';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Deadlift (Barbell)' AND citation='Rivera 2021';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Romanian Deadlift (Barbell)' AND citation='Rivera 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Bench Press (Barbell)' AND citation='Rodriguez-Ridao 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammerstrength Incline Chest Press' AND citation='Rodriguez-Ridao 2020';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Hammerstrength Incline Chest Press' AND citation='Rodriguez-Ridao 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Incline Bench Press (Barbell)' AND citation='Rodriguez-Ridao 2020';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Incline Bench Press (Barbell)' AND citation='Rodriguez-Ridao 2020';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammer Curl (Dumbbell)' AND citation='Schoenfeld 2015';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammer Curls' AND citation='Schoenfeld 2015';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hip Abduction (Machine)' AND citation='Selkowitz 2016';
UPDATE exercise_muscle SET citation='helms-2018-lv4-exercise-selection.md' WHERE exercise_name='Chin-Up' AND citation='Sola 1973';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Lat Pulldown (Cable)' AND citation='Warneke 2023';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Incline Chest Fly (Dumbbell)' AND citation='Wolf 2025';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Low Cable Chest Fly' AND citation='Wolf 2025';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Low Cable Fly Crossovers' AND citation='Wolf 2025';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammer Curl (Dumbbell)' AND citation='Yagiz 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Hammer Curls' AND citation='Yagiz 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Reverse Curl (Dumbbell)' AND citation='Yagiz 2022';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Crossover Fly' AND citation='Zabaleta-Korta 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Cable Fly Crossovers' AND citation='Zabaleta-Korta 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Chest Fly (Dumbbell)' AND citation='Zabaleta-Korta 2021';
UPDATE exercise_muscle SET citation='schoenfeld-2021-ch8-program-design.md' WHERE exercise_name='Preacher Curl (Barbell)' AND citation='Zabaleta-Korta 2023 / Nunes 2020';

-- ── 3b. rows the vault CONTRADICTS -> science stripped, mapping kept ───────
-- Directly contradicted by ch8: 'Shoulder press: primarily anterior head' and 'internally rotated shoulder 
UPDATE exercise_muscle SET citation=NULL, region=NULL, length_bias=NULL, rationale=NULL WHERE exercise_name='Arnold Press (Dumbbell)' AND citation='Campos 2020';
-- Same contradiction as the Arnold Press side-delt row: ch8 says the shoulder press is primarily ANTERIOR h
UPDATE exercise_muscle SET citation=NULL, region=NULL, length_bias=NULL, rationale=NULL WHERE exercise_name='Overhead Press (Dumbbell)' AND citation='Campos 2020';
-- Contradicted by ch8: 'Glute medius/minimus: frontal plane ABDUCTION ONLY (cable hip side raise, clamshell
UPDATE exercise_muscle SET citation=NULL, region=NULL, length_bias=NULL, rationale=NULL WHERE exercise_name='Step Up (Dumbbell)' AND citation='DiStefano 2009';

-- ── 3c. unsupported-but-plausible -> marked, never fabricated ──────────────
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Barbell Shrug' AND citation='Andersen 2008' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Dumbbell Shrug' AND citation='Andersen 2008' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Upright Row (Barbell)' AND citation='Andersen 2008' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Upright Row (Barbell)' AND citation='Andersen 2008' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Face Pull' AND citation='Arlotta 2011' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Hip Adduction (Machine)' AND citation='Brandt 2013' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Bench Press (Dumbbell)' AND citation='Christian 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Kickback (Cable)' AND citation='DiStefano 2009' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Face Pull' AND citation='Fennell 2016' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Calf Raise (Machine)' AND citation='Kassiano 2023b' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Standing Machine Calf Press' AND citation='Kassiano 2023b' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Leg Press (Machine)' AND citation='Kubo 2019' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Lateral Raise (Cable)' AND citation='Larsen 2025' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Cable Core Pallof Press' AND citation='Mandroukas 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Pallof Press (Cable)' AND citation='Mandroukas 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Deadlift (Barbell)' AND citation='Nagao 2019' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Bicep Curl (Cable)' AND citation='Nunes 2020' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Cable Curl' AND citation='Nunes 2020' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Bicep Curl (Dumbbell)' AND citation='Oliveira 2009' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Concentration Curl (Dumbbell)' AND citation='Oliveira 2009' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Preacher Curl (Dumbbell)' AND citation='Oliveira 2009' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Seated Dumbbell Curl' AND citation='Oliveira 2009' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Bulgarian Split Squat (Dumbbell)' AND citation='Plotkin 2023' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Lunge (Barbell)' AND citation='Plotkin 2023' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Face Pull' AND citation='Rabello 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Bicep Curl (Barbell)' AND citation='Schoenfeld 2015' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Dip (Chest)' AND citation='Wolf 2025' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Palms-Down Dumbbell Wrist Curl' AND citation='Yagiz 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Seated Palms Up Wrist Curl' AND citation='Yagiz 2022' AND citation NOT LIKE 'UNGROUNDED%';
UPDATE exercise_muscle SET citation='UNGROUNDED: '||citation WHERE exercise_name='Seated Wrist Extension (Barbell)' AND citation='Yagiz 2022' AND citation NOT LIKE 'UNGROUNDED%';
